apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "oasgen-provider.fullname" . }}-{{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name:  {{ include "oasgen-provider.fullname" . }}-{{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ include "oasgen-provider.fullname" . }}
  namespace: {{ .Release.Namespace }}
