apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oasgen-provider.fullname" . }}
  labels:
    {{- include "oasgen-provider.labels" . | nindent 4 }}
data:
  CORE_PROVIDER_DEBUG: "{{ .Values.env.CORE_PROVIDER_DEBUG }}"
  CDC_IMAGE_TAG: {{ .Values.env.CDC_IMAGE_TAG }}
