apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oasgen-provider.fullname" . }}-rbac-configmap
data:
  serviceaccount.yaml: |
{{ tpl (.Files.Get "assets/rdc/rbac/serviceaccount.yaml") . | indent 4 }}
  clusterrole.yaml: |
{{ tpl (.Files.Get "assets/rdc/rbac/clusterrole.yaml") . | indent 4 }}
  clusterrolebinding.yaml: |
{{ tpl (.Files.Get "assets/rdc/rbac/clusterrolebinding.yaml") . | indent 4 }}
  role.yaml: |
{{ tpl (.Files.Get "assets/rdc/rbac/role.yaml") . | indent 4 }}
  rolebinding.yaml: |
{{ tpl (.Files.Get "assets/rdc/rbac/rolebinding.yaml") . | indent 4 }}