apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oasgen-provider.fullname" . }}-rbac-configmap
data:
  serviceaccount.yaml: |
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: {{`{{ .name }}`}}
      namespace: {{`{{ .namespace }}`}}
  clusterrole.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: {{`{{ .name }}`}}
    rules:
    - apiGroups: ["apiextensions.k8s.io"]
      resources: ["customresourcedefinitions"]
      verbs: ["get", "list"]
    - apiGroups: [""]
      resources: ["configmaps"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["get", "list", "watch"]
  clusterrolebinding.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: {{`{{ .name }}`}}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: ClusterRole
      name: {{`{{ .name }}`}}
    subjects:
    - kind: ServiceAccount
      name: {{`{{ .serviceAccount }}`}}
      namespace: {{`{{ .saNamespace }}`}}
  role.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: Role
    metadata:
      name: {{`{{ .name }}`}}
      namespace: {{`{{ .namespace }}`}}
    rules:
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["create", "patch", "update"]
    - apiGroups: ["swaggergen.krateo.io"]
      resources: ["restdefinitions", "restdefinitions/status"]
      verbs: ["get", "list", "watch"]
    - apiGroups: [ {{`{{ .apiGroup }}`}}]
      resources: ["{{`{{ .resource }}`}}", "{{`{{ .resource }}`}}/status"]
      verbs: ["*"]
    {{`{{- if .authentications }}`}}
    - apiGroups: [{{`{{ .apiGroup }}`}}]
      resources:
      {{`{{- range .authentications }}`}}
      - "{{`{{ . }}`}}"
      {{`{{- end }}`}}
      verbs: ["*"]
    {{`{{- end }}`}}
  rolebinding.yaml: |
    apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: {{`{{ .name }}`}}
      namespace: {{`{{ .namespace }}`}}
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: {{`{{ .name }}`}}
    subjects:
    - kind: ServiceAccount
      name: {{`{{ .serviceAccount }}`}}
      namespace: {{`{{ .saNamespace }}`}}