apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "oasgen-provider.fullname" . }}-rdc-deployment
  labels:
    {{- include "oasgen-provider.labels" . | nindent 4 }}
data:
  deployment.yaml: |
{{ tpl (.Files.Get "assets/rdc/deployment.yaml") . | indent 4 }}