apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  annotations:
     "krateo.io/connector-verbose": "true"
  name: postgresql-repo
  namespace: demo-system
spec:
  chart:
    url: https://charts.bitnami.com/bitnami
    version: "12.8.3"
    repo: postgresql

