apiVersion: core.krateo.io/v1alpha1
kind: CompositionDefinition
metadata:
  annotations:
     "krateo.io/connector-verbose": "true"
  name: fireworks-private
  namespace: krateo-system
spec:
  chart:
    url: oci://registry-1.docker.io/matteogastaldello/fireworks-app
    version: "0.1.0"
    credentials:
      username: matteogastaldello
      passwordRef: # reference to a secret
        key: token
        name: docker-hub
        namespace: default

