---
apiVersion: core.krateo.io/v1alpha1
kind: SchemaDefinition
metadata:
  annotations:
     "krateo.io/connector-verbose": "true"
  name: fireworksapp
  namespace: demo-system
spec:
  schema:
    kind: FireWorksApp
    url: https://raw.githubusercontent.com/krateoplatformops/krateo-v2-template-fireworksapp/main/chart/values.schema.json