---
apiVersion: core.krateo.io/v1alpha1
kind: SchemaDefinition
metadata:
  annotations:
     "krateo.io/connector-verbose": "true"
  name: sample
  namespace: demo-system
spec:
  schema:
    kind: Sample
    url: http://localhost:8100/values.schema.json