kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: def-checks
  namespace: default
spec:
  deletionPolicy: Delete
  oasPath: https://raw.githubusercontent.com/matteogastaldello/azuredevops-oas3/e6a44e4276ff0c6bc69698790c1355b5d20d5f41/approvalandchecks/pipelinechecks.yaml
  resourceGroup: azure.devops.com
  resource:
    kind: Checks
    identifiers:
    - id
    - resource.id
    verbsDescription:
    - action: create
      method: POST
      path: /{organization}/{project}/_apis/pipelines/checks/configurations
    - action: findby
      method: GET
      path: /{organization}/{project}/_apis/pipelines/checks/configurations
      altFieldMapping:
        id: resource.id
    - action: delete
      method: DELETE
      path: /{organization}/{project}/_apis/pipelines/checks/configurations/{id}
    - action: get
      method: GET
      path: /{organization}/{project}/_apis/pipelines/checks/configurations/{id}
    - action: update
      method: PATCH
      path: /{organization}/{project}/_apis/pipelines/checks/configurations/{id}