kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: def-endpoints
  namespace: default
  annotations:
    krateo.io/connector-verbose: "true"
  labels:
    krateo.io/crd-group: azure.devops.com
spec:
  deletionPolicy: Delete 
  oasPath: "https://raw.githubusercontent.com/matteogastaldello/azuredevops-oas3/7f0d5bb17d00bccad8dada591aa17a31deda55f0/serviceEndpoint/endpoints.yaml"
  resourceGroup: azure.devops.com
  resource: 
    # ownerRefs: 
    #   - field: project
    #     groupVersionKind:
    #       group: azure.devops.com
    #       version: v1alpha1
    #       kind: TeamProject
    compareList: ["serviceEndpointProjectReferences", "type"]
    kind: ServiceEndpoint
    identifiers: ["id", "name"]
    verbsDescription:
      - action: create
        method: POST
        path: /{organization}/_apis/serviceendpoint/endpoints
      - action: get
        method: GET
        path: /{organization}/{project}/_apis/serviceendpoint/endpoints/{endpointId}
        altFieldMapping:  # Optional: with the format <newField>: <oldField>
          id: endpointId
      - action: delete
        method: DELETE
        path: /{organization}/_apis/serviceendpoint/endpoints/{endpointId}
        altFieldMapping:  # Optional: with the format <newField>: <oldField>
          id: endpointId
          serviceEndpointProjectReferences[].projectReference.id: projectIds #ids will be comma separated
      - action: findby
        method: GET
        path: /{organization}/{project}/_apis/serviceendpoint/endpoints



  