kind: RestDefinition
apiVersion: swaggergen.krateo.io/v1alpha1
metadata:
  name: definition-environments
  namespace: default
spec:
  deletionPolicy: Delete
  oasPath: https://raw.githubusercontent.com/matteogastaldello/azuredevops-oas3/17741860d6bb9eaf5d1b86c09056cba5707d7748/environments/environments.yaml
  resourceGroup: azure.devops.com
  resource: 
    kind: EnvironmentInstance
    compareList: ["name", "description"]
    identifiers: [id, name]
    verbsDescription:
    - action: get
      method: GET
      path: /{organization}/{project}/_apis/distributedtask/environments/{environmentId}
      altFieldMapping:  # Optional: with the format <newField>: <oldField>
        id: environmentId
    - action: findby
      method: GET
      path: /{organization}/{project}/_apis/distributedtask/environments
    - action: create
      method: POST
      path: /{organization}/{project}/_apis/distributedtask/environments
    - action: update
      method: PATCH
      path: /{organization}/{project}/_apis/distributedtask/environments/{environmentId}
      altFieldMapping:  # Optional: with the format <newField>: <oldField>
        id: environmentId
    - action: delete
      method: DELETE
      path: /{organization}/{project}/_apis/distributedtask/environments/{environmentId}
      altFieldMapping:  # Optional: with the format <newField>: <oldField>
        id: environmentId



  