apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ "{{" }} .name {{ "}}" }}-configmap
  namespace: {{ "{{" }} .namespace {{ "}}" }}
  labels:
    app.kubernetes.io/name: {{ "{{" }} trunc 63 .name {{ "}}" }}
    app.kubernetes.io/instance: {{ "{{" }} trunc 63 .resource {{ "}}" }}
    app.kubernetes.io/version: {{ "{{" }} trunc 63 .apiVersion {{ "}}" }}
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: krateoplatformops
    app.kubernetes.io/managed-by: krateo
data:
  {{- range $key, $value := .Values.rdc.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}